// src/components/pages/ProjectInput.jsx
import React, { useState, useEffect } from 'react';
import axios from 'axios';

function ProjectInput() {
    const [isModalOpen, setIsModalOpen] = useState(false);
    const [projects, setProjects] = useState([]);
    const [loading, setLoading] = useState(true);
    const [error, setError] = useState(null);

    useEffect(() => {
        const fetchProjects = async () => {
            try {
                const response = await axios.get(`${import.meta.env.VITE_BACKEND_URL}/projects`);
                setProjects(response.data);
                setError(null);
            } catch (err) {
                console.error("Error fetching projects:", err);
                setError("Failed to load projects. Please try again later.");
            } finally {
                setLoading(false);
            }
        };

        fetchProjects();
    }, []);

    const handleOpenModal = () => setIsModalOpen(true);
    const handleCloseModal = () => setIsModalOpen(false);
    const handleSubmitProject = async (newProject) => {
        try {
            const response = await axios.post(`${import.meta.env.VITE_BACKEND_URL}/projects/`, {
                name: newProject.name,
                description: `Customer: ${newProject.customer}\nType: ${newProject.type}\nManager: ${newProject.manager}`,
                status: newProject.status || '运行中',
                end_date: newProject.projectTime
            });
            
            setProjects([...projects, response.data]);
            setError(null);
            handleCloseModal();
        } catch (err) {
            console.error("Error creating project:", err);
            setError("Failed to create project. Please try again later.");
        }
    };

    return (
        <div>
            <div style={{ textAlign: 'right', marginBottom: '1rem' }}>
                <button onClick={handleOpenModal}>创建</button>
            </div>

            {isModalOpen && (
                <ProjectInputModal
                    onClose={handleCloseModal}
                    onSubmit={handleSubmitProject}
                />
            )}

            {loading ? (
                <div style={{ textAlign: 'center', padding: '2rem' }}>
                    加载中...
                </div>
            ) : error ? (
                <div style={{ color: 'red', textAlign: 'center', padding: '2rem' }}>
                    {error}
                </div>
            ) : (
                <table>
                    <thead>
                        <tr>
                            <th>项目编号</th>
                            <th>项目名称</th>
                            <th>客户名称</th>
                            <th>项目类型</th>
                            <th>零件数量</th>
                            <th>状态</th>
                            <th>进度</th>
                            <th>创建时间</th>
                            <th>项目工程</th>
                            <th>负责人</th>
                        </tr>
                    </thead>
                    <tbody>
                        {projects.map((project) => (
                            <tr key={project.id}>
                                <td>{project.id}</td>
                                <td>{project.name}</td>
                                <td>{project.description}</td>
                                <td>{project.type || '-'}</td>
                                <td>{project.quantity || '-'}</td>
                                <td>{project.status}</td>
                                <td>{project.progress || '0%'}</td>
                                <td>{new Date(project.start_date).toLocaleDateString()}</td>
                                <td>{project.end_date ? new Date(project.end_date).toLocaleDateString() : '-'}</td>
                                <td>{project.manager || '-'}</td>
                            </tr>
                        ))}
                    </tbody>
                </table>
            )}
        </div>
    );
}

function ProjectInputModal({ onClose, onSubmit }) {
    const [formData, setFormData] = useState({
        id: '',
        name: '',
        customer: '',
        type: '',
        quantity: '',
        status: '运行中',
        progress: '0%',
        createTime: '',
        projectTime: '',
        manager: '',
    });

    const handleInputChange = (e) => {
        const { name, value } = e.target;
        setFormData({ ...formData, [name]: value });
    };

    const handleSubmit = (e) => {
        e.preventDefault();
        onSubmit(formData);
    };

    return (
        <div className="modal-overlay">
            <div className="modal-content">
                <h2>项目录入</h2>
                <form onSubmit={handleSubmit}>
                    <div>
                        <label>项目编号:</label>
                        <input
                            type="text"
                            name="id"
                            value={formData.id}
                            onChange={handleInputChange}
                            required
                        />
                    </div>
                    <div>
                        <label>项目名称:</label>
                        <input
                            type="text"
                            name="name"
                            value={formData.name}
                            onChange={handleInputChange}
                            required
                        />
                    </div>
                    <div>
                        <label>客户名称:</label>
                        <input
                            type="text"
                            name="customer"
                            value={formData.customer}
                            onChange={handleInputChange}
                            required
                        />
                    </div>
                    <div>
                        <label>项目类型:</label>
                        <input
                            type="text"
                            name="type"
                            value={formData.type}
                            onChange={handleInputChange}
                            required
                        />
                    </div>
                    <div>
                        <label>零件数量:</label>
                        <input
                            type="number"
                            name="quantity"
                            value={formData.quantity}
                            onChange={handleInputChange}
                            required
                        />
                    </div>
                    <div>
                        <label>创建时间:</label>
                        <input
                            type="date"
                            name="createTime"
                            value={formData.createTime}
                            onChange={handleInputChange}
                            required
                        />
                    </div>
                    <div>
                        <label>项目工程:</label>
                        <input
                            type="date"
                            name="projectTime"
                            value={formData.projectTime}
                            onChange={handleInputChange}
                            required
                        />
                    </div>
                    <div>
                        <label>负责人:</label>
                        <input
                            type="text"
                            name="manager"
                            value={formData.manager}
                            onChange={handleInputChange}
                            required
                        />
                    </div>
                    <div style={{ marginTop: '1rem' }}>
                        <button type="submit">提交</button>
                        <button type="button" onClick={onClose}>取消</button>
                    </div>
                </form>
            </div>
        </div>
    );
}

export default ProjectInput;

// frontend/views/ProjectInput.vue
<template>
  <div class="project-input">
    <div class="header">
      <el-button type="primary" @click="dialogVisible = true">
        创建项目
      </el-button>
    </div>

    <!-- 项目列表表格 -->
    <el-table
      v-loading="loading"
      :data="projects"
      style="width: 100%"
      border
    >
      <el-table-column prop="id" label="项目编号" width="100" />
      <el-table-column prop="name" label="项目名称" width="150" />
      <el-table-column prop="customer" label="客户名称" width="150" />
      <el-table-column prop="type" label="项目类型" width="120" />
      <el-table-column prop="parts_count" label="零件数量" width="100" />
      <el-table-column prop="status" label="状态" width="100">
        <template #default="{ row }">
          <el-tag :type="getStatusType(row.status)">{{ row.status }}</el-tag>
        </template>
      </el-table-column>
      <el-table-column prop="progress" label="进度" width="200">
        <template #default="{ row }">
          <el-progress :percentage="row.progress || 0" />
        </template>
      </el-table-column>
      <el-table-column prop="start_date" label="创建时间" width="180">
        <template #default="{ row }">
          {{ formatDate(row.start_date) }}
        </template>
      </el-table-column>
      <el-table-column prop="end_date" label="截止日期" width="180">
        <template #default="{ row }">
          {{ formatDate(row.end_date) }}
        </template>
      </el-table-column>
      <el-table-column prop="manager" label="负责人" width="120" />
    </el-table>

    <!-- 创建项目对话框 -->
    <el-dialog
      v-model="dialogVisible"
      title="创建新项目"
      width="50%"
      :before-close="handleClose"
    >
      <el-form
        ref="formRef"
        :model="form"
        :rules="rules"
        label-width="120px"
      >
        <el-form-item label="项目名称" prop="name">
          <el-input v-model="form.name" />
        </el-form-item>
        <el-form-item label="客户名称" prop="customer">
          <el-input v-model="form.customer" />
        </el-form-item>
        <el-form-item label="项目类型" prop="type">
          <el-select v-model="form.type" placeholder="请选择项目类型">
            <el-option label="维修" value="维修" />
            <el-option label="保养" value="保养" />
            <el-option label="改造" value="改造" />
          </el-select>
        </el-form-item>
        <el-form-item label="负责人" prop="manager">
          <el-input v-model="form.manager" />
        </el-form-item>
        <el-form-item label="创建时间" prop="start_date">
          <el-date-picker
            v-model="form.start_date"
            type="datetime"
            placeholder="选择创建时间"
          />
        </el-form-item>
        <el-form-item label="截止日期" prop="end_date">
          <el-date-picker
            v-model="form.end_date"
            type="datetime"
            placeholder="选择截止日期"
          />
        </el-form-item>
      </el-form>
      <template #footer>
        <span class="dialog-footer">
          <el-button @click="dialogVisible = false">取消</el-button>
          <el-button type="primary" @click="submitForm">
            确认
          </el-button>
        </span>
      </template>
    </el-dialog>
  </div>
</template>

<script setup>
import { ref, onMounted } from 'vue'
import { ElMessage } from 'element-plus'
import axios from 'axios'

const loading = ref(false)
const dialogVisible = ref(false)
const projects = ref([])
const formRef = ref(null)

const form = ref({
  name: '',
  customer: '',
  type: '',
  manager: '',
  start_date: '',
  end_date: '',
  status: '运行中'
})

const rules = {
  name: [{ required: true, message: '请输入项目名称', trigger: 'blur' }],
  customer: [{ required: true, message: '请输入客户名称', trigger: 'blur' }],
  type: [{ required: true, message: '请选择项目类型', trigger: 'change' }],
  manager: [{ required: true, message: '请输入负责人', trigger: 'blur' }],
  start_date: [{ required: true, message: '请选择创建时间', trigger: 'change' }],
  end_date: [{ required: true, message: '请选择截止日期', trigger: 'change' }]
}

// 获取项目列表
const fetchProjects = async () => {
  loading.value = true
  try {
    const response = await axios.get(`${import.meta.env.VITE_BACKEND_URL}/projects`)
    projects.value = response.data
  } catch (error) {
    console.error('Error fetching projects:', error)
    ElMessage.error('加载项目失败，请稍后重试')
  } finally {
    loading.value = false
  }
}

// 提交表单
const submitForm = async () => {
  if (!formRef.value) return
  
  await formRef.value.validate(async (valid) => {
    if (valid) {
      try {
        const response = await axios.post(
          `${import.meta.env.VITE_BACKEND_URL}/projects/`,
          form.value
        )
        projects.value.push(response.data)
        ElMessage.success('项目创建成功')
        dialogVisible.value = false
        resetForm()
      } catch (error) {
        console.error('Error creating project:', error)
        ElMessage.error('创建项目失败，请稍后重试')
      }
    }
  })
}

// 重置表单
const resetForm = () => {
  if (formRef.value) {
    formRef.value.resetFields()
  }
  form.value = {
    name: '',
    customer: '',
    type: '',
    manager: '',
    start_date: '',
    end_date: '',
    status: '运行中'
  }
}

// 关闭对话框
const handleClose = (done) => {
  resetForm()
  done()
}

// 格式化日期
const formatDate = (date) => {
  if (!date) return ''
  return new Date(date).toLocaleString('zh-CN')
}

// 获取状态标签类型
const getStatusType = (status) => {
  const types = {
    '运行中': 'primary',
    '已完成': 'success',
    '已暂停': 'warning',
    '已取消': 'danger'
  }
  return types[status] || 'info'
}

onMounted(() => {
  fetchProjects()
})
</script>

<style scoped>
.project-input {
  padding: 20px;
}

.header {
  margin-bottom: 20px;
  text-align: right;
}

.dialog-footer {
  display: flex;
  justify-content: flex-end;
  gap: 10px;
}

:deep(.el-dialog__body) {
  padding: 20px 40px;
}
</style>
